# Generated by Django 4.2.25 on 2025-10-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_github_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
