# Generated by Django 5.2.6 on 2025-11-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_last_github_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown/ CommonMark'), ('image/png', 'Image/PNG'), ('image/jpeg', 'Image/JPEG'), ('image/gif', 'Image/GIF'), ('image/bmp', 'Image/BMP'), ('image/webp', 'Image/WEBP')], default='text/plain', max_length=20),
        ),
    ]
