# Generated by Django 5.2.7 on 2025-10-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_host_author_url_alter_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
