# Generated by Django 4.2.25 on 2025-10-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_author_description_alter_author_profileimage_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown/ CommonMark'), ('image/png', 'PNG Image'), ('image/jpeg', 'JPEG Image'), ('image/gif', 'GIF Image'), ('image/bmp', 'BMP Image'), ('image/webp', 'WebP Image')], default='text/plain', max_length=20),
        ),
    ]
