# Generated by Django 4.2.25 on 2025-11-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_image_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
