# Generated by Django 5.2.6 on 2025-11-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='origin',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='origin',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='like',
            name='origin',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['origin'], name='authors_com_origin_05637c_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['origin'], name='authors_com_origin_2e5bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['origin'], name='authors_lik_origin_9c9816_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['origin'], name='authors_pos_origin_2c80b6_idx'),
        ),
    ]
