# Generated by Django 4.2.25 on 2025-11-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_remotenode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown/ CommonMark')], default='text/plain', max_length=20),
        ),
    ]
