# Generated by Django 4.2.25 on 2025-11-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_alter_post_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
