# Generated by Django 5.2.6 on 2025-11-17 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_alter_post_contenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxReceipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(help_text='The post that was delivered to the inbox', on_delete=django.db.models.deletion.CASCADE, related_name='inbox_receipts', to='authors.post')),
                ('recipient', models.ForeignKey(help_text='The author who received this post in their inbox', on_delete=django.db.models.deletion.CASCADE, related_name='inbox_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', 'post'], name='authors_inb_recipie_ddf6ae_idx'), models.Index(fields=['received_at'], name='authors_inb_receive_338755_idx')],
                'unique_together': {('recipient', 'post')},
            },
        ),
    ]
