# Generated by Django 4.2.25 on 2025-11-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0010_alter_image_content_type_alter_image_id'),
        ('authors', '0010_inboxreceipt'),
    ]

    operations = [
    ]
