# Generated by Django 5.2.6 on 2025-11-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_alter_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown/ CommonMark'), ('image/png;base64', 'Image (PNG)'), ('image/jpeg;base64', 'Image (JPEG)'), ('application/base64', 'Image (Other)')], default='text/plain', max_length=30),
        ),
    ]
