# Generated by Django 4.2.25 on 2025-11-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0014_populate_post_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown/ CommonMark'), ('image', 'Image'), ('image/png;base64', 'Image (PNG)'), ('image/jpeg;base64', 'Image (JPEG)'), ('application/base64', 'Image (Other)')], default='text/plain', max_length=30),
        ),
    ]
