# Generated by Django 4.2.25 on 2025-11-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0015_alter_post_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PUBLIC_UNLISTED', 'Public Unlisted'), ('FRIENDS', 'Friends Only'), ('DELETED', 'Deleted')], default='PUBLIC', max_length=20),
        ),
    ]
